apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: dev-scdf-basic-auth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        auth: "{{ htpasswd .username .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: /common
        property: username
    - secretKey: password
      remoteRef:
        key: /common
        property: password